name: Run Cypress Tests

on:
  push:
    branches:
      - master  # Trigger on push to 'master'
  pull_request:
    branches:
      - master  # Trigger on pull requests to 'master'
  schedule:
    - cron: '*/10 * * * *'  # Run every day at 9:00 AM UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install
      working-directory: ./  # Ensure this points to the correct directory

    - name: Run Cypress tests
      run: npx cypress run --browser chrome
      working-directory: ./  # Ensure this points to the correct directory

    # Upload the test artifacts (videos and screenshots) as GitHub Actions artifacts
    - name: Upload Cypress test artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cypress-artifacts
        path: |
          cypress/videos
          cypress/screenshots


    - name: Send success email
      if: success()
      run: |
        node notify.js success
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}

    # 6. Send failure notification via email
    - name: Send failure email
      if: failure()
      run: |
        node notify.js failure
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}

