name: Run Cypress Tests

on:
  push:
    branches:
      - master  # Trigger on push to 'master'
  pull_request:
    branches:
      - master  # Trigger on pull requests to 'master'
  schedule:
    - cron: '0 9 * * *'  # Run every day at 9:00 AM UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install
      working-directory: ./  # Ensure this points to the correct directory

    - name: Run Cypress tests
      run: npx cypress run --browser chrome
      working-directory: ./  # Ensure this points to the correct directory

